global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'fast'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fast:8001']
