global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['43.200.252.76:80']
        labels:
          __metrics_path__: '/metrics/'

  - job_name: 'fastapi'
    static_configs:
      - targets: ['43.200.252.76:80']
        labels:
          __metrics_path__: '/api/metrics/'
