services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django_app
      - fast_app
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../APP_Django/static:/app/static
      - ../../APP_Django/media:/app/media
    networks:
      - mynetwork

  django_app:
    build:
      context: ../../
      dockerfile: Configurations/docker/DjangoDockerfile
    command: >
      sh -c "until pg_isready -h django_db -p 5432 -U postgres; do echo 'Waiting for DB...'; sleep 2; done &&
             python manage.py migrate &&
             gunicorn -k uvicorn.workers.UvicornWorker config.asgi:application --bind 0.0.0.0:8000 --workers 1 --threads 2"
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    volumes:
      - ../../:/app
    expose:
      - "8000"
    networks:
      - mynetwork
    depends_on:
      django_db:
        condition: service_healthy

  fast_app:
    build:
      context: ../../
      dockerfile: Configurations/docker/FastDockerfile
    command: >
      sh -c "until pg_isready -h fast_db -p 5432 -U postgres; do echo 'Waiting for DB...'; sleep 2; done &&
             uvicorn main:app --host 0.0.0.0 --port 8001 --workers 1"
    restart: always
    volumes:
      - ../../:/app
    expose:
      - "8001"
    networks:
      - mynetwork
    depends_on:
      fast_db:
        condition: service_healthy

  django_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fast_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app_fast
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /home/Today-s-Write/Configurations/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  grafana_data:
