version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django_app
      - fast_app
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../APP_Django/static:/app/static
      - ../../APP_Django/media:/app/media
    networks:
      - mynetwork

  django_app:
    build:
      context: ../../
      dockerfile: Configurations/docker/DjangoDockerfile
    command: >
      sh -c "while ! nc -z django_db 5432; do sleep 1; done &&
            python manage.py migrate &&
            gunicorn -k uvicorn.workers.UvicornWorker config.asgi:application --bind 0.0.0.0:8000 --workers 1 --threads 2"
    restart: always
    volumes:
      - ../../:/app
    expose:
      - "8000"
    networks:
      - mynetwork

  fast_app:
    build:
      context: ../../
      dockerfile: Configurations/docker/FastDockerfile
    command: >
      sh -c "while ! nc -z fast_db 5432; do sleep 1; done &&
             uvicorn main:app --host 0.0.0.0 --port 8001 --workers 1"
    restart: always
    volumes:
      - ../../:/app
    expose:
      - "8001"
    networks:
      - mynetwork

  django_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    networks:
      - mynetwork

  fast_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app_fast
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
